version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: buscador
      POSTGRES_USER: buscador
      POSTGRES_PASSWORD: buscador
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://buscador:buscador@postgres:5432/buscador
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    ports:
      - '4000:4000'

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api
    depends_on:
      - api
    ports:
      - '3000:3000'

volumes:
  postgres_data:
